use crate::disassembler::CpuAnalysisState;

#[derive(Debug, Clone, Copy)]
pub enum AddressingMode {
    Implied,
    ImmediateMFlag,
    ImmediateXFlag,
    ImmediateByte,
    PcRelative,
    PcRelativeLong,
    Direct,
    DirectIndexedX,
    DirectIndexedY,
    Indirect,
    IndexedIndirectX,
    IndirectIndexedY,
    IndirectLong,
    IndirectIndexedYLong,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    AbsoluteLong,
    AbsoluteLongX,
    StackRelative,
    StackRelativeIndirectIndexed,
    AbsoluteIndirect,
    AbsoluteIndirectLong,
    AbsoluteIndirectIndexed,
    BlockMove,
}

impl AddressingMode {
    pub(in crate::disassembler) fn operand_bytes(
        &self,
        analysis_state: &CpuAnalysisState,
    ) -> usize {
        match *self {
            Implied => 0,
            ImmediateMFlag => 2 - (analysis_state.reg.m | analysis_state.reg.e) as usize,
            ImmediateXFlag => 2 - (analysis_state.reg.x | analysis_state.reg.e) as usize,
            ImmediateByte => 1,
            PcRelative => 1,
            PcRelativeLong => 2,
            Direct => 1,
            DirectIndexedX => 1,
            DirectIndexedY => 1,
            Indirect => 1,
            IndexedIndirectX => 1,
            IndirectIndexedY => 1,
            IndirectLong => 1,
            IndirectIndexedYLong => 1,
            Absolute => 2,
            AbsoluteX => 2,
            AbsoluteY => 2,
            AbsoluteLong => 3,
            AbsoluteLongX => 3,
            StackRelative => 1,
            StackRelativeIndirectIndexed => 1,
            AbsoluteIndirect => 2,
            AbsoluteIndirectLong => 2,
            AbsoluteIndirectIndexed => 2,
            BlockMove => 2,
        }
    }

    pub fn is_indirect(&self) -> bool {
        matches!(
            *self,
            IndexedIndirectX
                | IndirectIndexedY
                | IndirectLong
                | IndirectIndexedYLong
                | StackRelativeIndirectIndexed
                | AbsoluteIndirect
                | AbsoluteIndirectLong
                | AbsoluteIndirectIndexed
        )
    }
}

#[rustfmt::skip]
#[derive(Debug, Clone, Copy)]
pub enum Instruction {
    ADC, AND, ASL, BCC, BCS, BEQ, BIT, BMI, BNE, BPL,
    BRA, BRK, BRL, BVC, BVS, CLC, CLD, CLI, CLV, CMP,
    COP, CPX, CPY, DEC, DEX, DEY, EOR, INC, INX, INY,
    JML, JMP, JSL, JSR, LDA, LDX, LDY, LSR, MVN, MVP,
    NOP, ORA, PEA, PEI, PER, PHA, PHB, PHD, PHK, PHP,
    PHX, PHY, PLA, PLB, PLD, PLP, PLX, PLY, REP, ROL,
    ROR, RTI, RTL, RTS, SBC, SEC, SED, SEI, SEP, STA,
    STP, STX, STY, STZ, TAX, TAY, TCD, TCS, TDC, TRB,
    TSB, TSC, TSX, TXA, TXS, TXY, TYA, TYX, WAI, WDM,
    XBA, XCE,
}

#[derive(Debug, Clone, Copy)]
pub struct CpuInstructionData {
    pub instruction: Instruction,
    pub mode: AddressingMode,
}

impl CpuInstructionData {
    pub fn mnemonic(&self) -> String {
        format!("{:?}", self.instruction)
    }
}

impl crate::disassembler::InstructionData<CpuAnalysisState> for CpuInstructionData {
    fn operand_bytes(&self, analysis_state: &CpuAnalysisState) -> usize {
        self.mode.operand_bytes(analysis_state)
    }
}

use AddressingMode::*;
use Instruction::*;
#[rustfmt::skip]
pub const CPU_INSTRUCTION_DATA: [CpuInstructionData; 256] = [
    //0x00 - 0x0f
    CpuInstructionData { instruction: BRK, mode: ImmediateByte },
    CpuInstructionData { instruction: ORA, mode: IndexedIndirectX },
    CpuInstructionData { instruction: COP, mode: ImmediateByte },
    CpuInstructionData { instruction: ORA, mode: StackRelative },
    CpuInstructionData { instruction: TSB, mode: Direct },
    CpuInstructionData { instruction: ORA, mode: Direct },
    CpuInstructionData { instruction: ASL, mode: Direct },
    CpuInstructionData { instruction: ORA, mode: IndirectLong },
    CpuInstructionData { instruction: PHP, mode: Implied },
    CpuInstructionData { instruction: ORA, mode: ImmediateMFlag },
    CpuInstructionData { instruction: ASL, mode: Implied },
    CpuInstructionData { instruction: PHD, mode: Implied },
    CpuInstructionData { instruction: TSB, mode: Absolute },
    CpuInstructionData { instruction: ORA, mode: Absolute },
    CpuInstructionData { instruction: ASL, mode: Absolute },
    CpuInstructionData { instruction: ORA, mode: AbsoluteLong },
    // 0x10 - 0x1f
    CpuInstructionData { instruction: BPL, mode: PcRelative },
    CpuInstructionData { instruction: ORA, mode: IndirectIndexedY },
    CpuInstructionData { instruction: ORA, mode: Indirect },
    CpuInstructionData { instruction: ORA, mode: StackRelativeIndirectIndexed },
    CpuInstructionData { instruction: TRB, mode: Direct },
    CpuInstructionData { instruction: ORA, mode: DirectIndexedX },
    CpuInstructionData { instruction: ASL, mode: DirectIndexedX },
    CpuInstructionData { instruction: ORA, mode: IndirectIndexedYLong },
    CpuInstructionData { instruction: CLC, mode: Implied },
    CpuInstructionData { instruction: ORA, mode: AbsoluteY },
    CpuInstructionData { instruction: INC, mode: Implied },
    CpuInstructionData { instruction: TCS, mode: Implied },
    CpuInstructionData { instruction: TRB, mode: Absolute },
    CpuInstructionData { instruction: ORA, mode: AbsoluteX },
    CpuInstructionData { instruction: ASL, mode: AbsoluteX },
    CpuInstructionData { instruction: ORA, mode: AbsoluteLongX },
    // 0x20 - 0x2f
    CpuInstructionData { instruction: JSR, mode: Absolute },
    CpuInstructionData { instruction: AND, mode: IndexedIndirectX },
    CpuInstructionData { instruction: JSL, mode: AbsoluteLong },
    CpuInstructionData { instruction: AND, mode: StackRelative },
    CpuInstructionData { instruction: BIT, mode: Direct },
    CpuInstructionData { instruction: AND, mode: Direct },
    CpuInstructionData { instruction: ROL, mode: Direct },
    CpuInstructionData { instruction: AND, mode: IndirectLong },
    CpuInstructionData { instruction: PLP, mode: Implied },
    CpuInstructionData { instruction: AND, mode: ImmediateMFlag },
    CpuInstructionData { instruction: ROL, mode: Implied },
    CpuInstructionData { instruction: PLD, mode: Implied },
    CpuInstructionData { instruction: BIT, mode: Absolute },
    CpuInstructionData { instruction: AND, mode: Absolute },
    CpuInstructionData { instruction: ROL, mode: Absolute },
    CpuInstructionData { instruction: AND, mode: AbsoluteLong },
    // 0x30 - 0x3f
    CpuInstructionData { instruction: BMI, mode: PcRelative },
    CpuInstructionData { instruction: AND, mode: IndirectIndexedY },
    CpuInstructionData { instruction: AND, mode: Indirect },
    CpuInstructionData { instruction: AND, mode: StackRelativeIndirectIndexed },
    CpuInstructionData { instruction: BIT, mode: DirectIndexedX },
    CpuInstructionData { instruction: AND, mode: DirectIndexedX },
    CpuInstructionData { instruction: ROL, mode: DirectIndexedX },
    CpuInstructionData { instruction: AND, mode: IndirectIndexedYLong },
    CpuInstructionData { instruction: SEC, mode: Implied },
    CpuInstructionData { instruction: AND, mode: AbsoluteY },
    CpuInstructionData { instruction: DEC, mode: Implied },
    CpuInstructionData { instruction: TSC, mode: Implied },
    CpuInstructionData { instruction: BIT, mode: AbsoluteX },
    CpuInstructionData { instruction: AND, mode: AbsoluteX },
    CpuInstructionData { instruction: ROL, mode: AbsoluteX },
    CpuInstructionData { instruction: AND, mode: AbsoluteLongX },
    // 0x40 - 0x4f
    CpuInstructionData { instruction: RTI, mode: Implied },
    CpuInstructionData { instruction: EOR, mode: IndexedIndirectX },
    CpuInstructionData { instruction: WDM, mode: ImmediateByte },
    CpuInstructionData { instruction: EOR, mode: StackRelative },
    CpuInstructionData { instruction: MVP, mode: BlockMove },
    CpuInstructionData { instruction: EOR, mode: Direct },
    CpuInstructionData { instruction: LSR, mode: Direct },
    CpuInstructionData { instruction: EOR, mode: IndirectLong },
    CpuInstructionData { instruction: PHA, mode: Implied },
    CpuInstructionData { instruction: EOR, mode: ImmediateMFlag },
    CpuInstructionData { instruction: LSR, mode: Implied },
    CpuInstructionData { instruction: PHK, mode: Implied },
    CpuInstructionData { instruction: JMP, mode: Absolute },
    CpuInstructionData { instruction: EOR, mode: Absolute },
    CpuInstructionData { instruction: LSR, mode: Absolute },
    CpuInstructionData { instruction: EOR, mode: AbsoluteLong },
    // 0x50 - 0x5f
    CpuInstructionData { instruction: BVC, mode: PcRelative },
    CpuInstructionData { instruction: EOR, mode: IndirectIndexedY },
    CpuInstructionData { instruction: EOR, mode: Indirect },
    CpuInstructionData { instruction: EOR, mode: StackRelativeIndirectIndexed },
    CpuInstructionData { instruction: MVN, mode: BlockMove },
    CpuInstructionData { instruction: EOR, mode: DirectIndexedX },
    CpuInstructionData { instruction: LSR, mode: DirectIndexedX },
    CpuInstructionData { instruction: EOR, mode: IndirectIndexedYLong },
    CpuInstructionData { instruction: CLI, mode: Implied },
    CpuInstructionData { instruction: EOR, mode: AbsoluteY },
    CpuInstructionData { instruction: PHY, mode: Implied },
    CpuInstructionData { instruction: TCD, mode: Implied },
    CpuInstructionData { instruction: JML, mode: AbsoluteLong },
    CpuInstructionData { instruction: EOR, mode: AbsoluteX },
    CpuInstructionData { instruction: LSR, mode: AbsoluteX },
    CpuInstructionData { instruction: EOR, mode: AbsoluteLongX },
    // 0x60 - 0x6f
    CpuInstructionData { instruction: RTS, mode: Implied },
    CpuInstructionData { instruction: ADC, mode: IndexedIndirectX },
    CpuInstructionData { instruction: PER, mode: Absolute },
    CpuInstructionData { instruction: ADC, mode: StackRelative },
    CpuInstructionData { instruction: STZ, mode: Direct },
    CpuInstructionData { instruction: ADC, mode: Direct },
    CpuInstructionData { instruction: ROR, mode: Direct },
    CpuInstructionData { instruction: ADC, mode: IndirectLong },
    CpuInstructionData { instruction: PLA, mode: Implied },
    CpuInstructionData { instruction: ADC, mode: ImmediateMFlag },
    CpuInstructionData { instruction: ROR, mode: Implied },
    CpuInstructionData { instruction: RTL, mode: Implied },
    CpuInstructionData { instruction: JMP, mode: AbsoluteIndirect },
    CpuInstructionData { instruction: ADC, mode: Absolute },
    CpuInstructionData { instruction: ROR, mode: Absolute },
    CpuInstructionData { instruction: ADC, mode: AbsoluteLong },
    // 0x70 - 0x7f
    CpuInstructionData { instruction: BVS, mode: PcRelative },
    CpuInstructionData { instruction: ADC, mode: IndirectIndexedY },
    CpuInstructionData { instruction: ADC, mode: Indirect },
    CpuInstructionData { instruction: ADC, mode: StackRelativeIndirectIndexed },
    CpuInstructionData { instruction: STZ, mode: DirectIndexedX },
    CpuInstructionData { instruction: ADC, mode: DirectIndexedX },
    CpuInstructionData { instruction: ROR, mode: DirectIndexedX },
    CpuInstructionData { instruction: ADC, mode: IndirectIndexedYLong },
    CpuInstructionData { instruction: SEI, mode: Implied },
    CpuInstructionData { instruction: ADC, mode: AbsoluteY },
    CpuInstructionData { instruction: PLY, mode: Implied },
    CpuInstructionData { instruction: TDC, mode: Implied },
    CpuInstructionData { instruction: JMP, mode: AbsoluteIndirectIndexed },
    CpuInstructionData { instruction: ADC, mode: AbsoluteX },
    CpuInstructionData { instruction: ROR, mode: AbsoluteX },
    CpuInstructionData { instruction: ADC, mode: AbsoluteLongX },
    // 0x80 - 0x8f
    CpuInstructionData { instruction: BRA, mode: PcRelative },
    CpuInstructionData { instruction: STA, mode: IndexedIndirectX },
    CpuInstructionData { instruction: BRL, mode: PcRelativeLong },
    CpuInstructionData { instruction: STA, mode: StackRelative },
    CpuInstructionData { instruction: STY, mode: Direct },
    CpuInstructionData { instruction: STA, mode: Direct },
    CpuInstructionData { instruction: STX, mode: Direct },
    CpuInstructionData { instruction: STA, mode: IndirectLong },
    CpuInstructionData { instruction: DEY, mode: Implied },
    CpuInstructionData { instruction: BIT, mode: ImmediateMFlag },
    CpuInstructionData { instruction: TXA, mode: Implied },
    CpuInstructionData { instruction: PHB, mode: Implied },
    CpuInstructionData { instruction: STY, mode: Absolute },
    CpuInstructionData { instruction: STA, mode: Absolute },
    CpuInstructionData { instruction: STX, mode: Absolute },
    CpuInstructionData { instruction: STA, mode: AbsoluteLong },
    // 0x90 - 0x9f
    CpuInstructionData { instruction: BCC, mode: PcRelative },
    CpuInstructionData { instruction: STA, mode: IndirectIndexedY },
    CpuInstructionData { instruction: STA, mode: Indirect },
    CpuInstructionData { instruction: STA, mode: StackRelativeIndirectIndexed },
    CpuInstructionData { instruction: STY, mode: DirectIndexedX },
    CpuInstructionData { instruction: STA, mode: DirectIndexedX },
    CpuInstructionData { instruction: STX, mode: DirectIndexedY },
    CpuInstructionData { instruction: STA, mode: IndirectIndexedYLong },
    CpuInstructionData { instruction: TYA, mode: Implied },
    CpuInstructionData { instruction: STA, mode: AbsoluteY },
    CpuInstructionData { instruction: TXS, mode: Implied },
    CpuInstructionData { instruction: TXY, mode: Implied },
    CpuInstructionData { instruction: STZ, mode: Absolute },
    CpuInstructionData { instruction: STA, mode: AbsoluteX },
    CpuInstructionData { instruction: STZ, mode: AbsoluteX },
    CpuInstructionData { instruction: STA, mode: AbsoluteLongX },
    // 0xa0 - 0xaf
    CpuInstructionData { instruction: LDY, mode: ImmediateXFlag },
    CpuInstructionData { instruction: LDA, mode: IndexedIndirectX },
    CpuInstructionData { instruction: LDX, mode: ImmediateXFlag },
    CpuInstructionData { instruction: LDA, mode: StackRelative },
    CpuInstructionData { instruction: LDY, mode: Direct },
    CpuInstructionData { instruction: LDA, mode: Direct },
    CpuInstructionData { instruction: LDX, mode: Direct },
    CpuInstructionData { instruction: LDA, mode: IndirectLong },
    CpuInstructionData { instruction: TAY, mode: Implied },
    CpuInstructionData { instruction: LDA, mode: ImmediateMFlag },
    CpuInstructionData { instruction: TAX, mode: Implied },
    CpuInstructionData { instruction: PLB, mode: Implied },
    CpuInstructionData { instruction: LDY, mode: Absolute },
    CpuInstructionData { instruction: LDA, mode: Absolute },
    CpuInstructionData { instruction: LDX, mode: Absolute },
    CpuInstructionData { instruction: LDA, mode: AbsoluteLong },
    // 0xb0 - 0xbf
    CpuInstructionData { instruction: BCS, mode: PcRelative },
    CpuInstructionData { instruction: LDA, mode: IndirectIndexedY },
    CpuInstructionData { instruction: LDA, mode: Indirect },
    CpuInstructionData { instruction: LDA, mode: StackRelativeIndirectIndexed },
    CpuInstructionData { instruction: LDY, mode: DirectIndexedX },
    CpuInstructionData { instruction: LDA, mode: DirectIndexedX },
    CpuInstructionData { instruction: LDX, mode: DirectIndexedY },
    CpuInstructionData { instruction: LDA, mode: IndirectIndexedYLong },
    CpuInstructionData { instruction: CLV, mode: Implied },
    CpuInstructionData { instruction: LDA, mode: AbsoluteY },
    CpuInstructionData { instruction: TSX, mode: Implied },
    CpuInstructionData { instruction: TYX, mode: Implied },
    CpuInstructionData { instruction: LDY, mode: AbsoluteX },
    CpuInstructionData { instruction: LDA, mode: AbsoluteX },
    CpuInstructionData { instruction: LDX, mode: AbsoluteY },
    CpuInstructionData { instruction: LDA, mode: AbsoluteLongX },
    // 0xc0 - 0xcf
    CpuInstructionData { instruction: CPY, mode: ImmediateXFlag },
    CpuInstructionData { instruction: CMP, mode: IndexedIndirectX },
    CpuInstructionData { instruction: REP, mode: ImmediateByte },
    CpuInstructionData { instruction: CMP, mode: StackRelative },
    CpuInstructionData { instruction: CPY, mode: Direct },
    CpuInstructionData { instruction: CMP, mode: Direct },
    CpuInstructionData { instruction: DEC, mode: Direct },
    CpuInstructionData { instruction: CMP, mode: IndirectLong },
    CpuInstructionData { instruction: INY, mode: Implied },
    CpuInstructionData { instruction: CMP, mode: ImmediateMFlag },
    CpuInstructionData { instruction: DEX, mode: Implied },
    CpuInstructionData { instruction: WAI, mode: Implied },
    CpuInstructionData { instruction: CPY, mode: Absolute },
    CpuInstructionData { instruction: CMP, mode: Absolute },
    CpuInstructionData { instruction: DEC, mode: Absolute },
    CpuInstructionData { instruction: CMP, mode: AbsoluteLong },
    // 0xd0 - 0xdf
    CpuInstructionData { instruction: BNE, mode: PcRelative },
    CpuInstructionData { instruction: CMP, mode: IndirectIndexedY },
    CpuInstructionData { instruction: CMP, mode: Indirect },
    CpuInstructionData { instruction: CMP, mode: StackRelativeIndirectIndexed },
    CpuInstructionData { instruction: PEI, mode: Indirect },
    CpuInstructionData { instruction: CMP, mode: DirectIndexedX },
    CpuInstructionData { instruction: DEC, mode: DirectIndexedX },
    CpuInstructionData { instruction: CMP, mode: IndirectIndexedYLong },
    CpuInstructionData { instruction: CLD, mode: Implied },
    CpuInstructionData { instruction: CMP, mode: AbsoluteY },
    CpuInstructionData { instruction: PHX, mode: Implied },
    CpuInstructionData { instruction: STP, mode: Implied },
    CpuInstructionData { instruction: JMP, mode: AbsoluteIndirectLong },
    CpuInstructionData { instruction: CMP, mode: AbsoluteX },
    CpuInstructionData { instruction: DEC, mode: AbsoluteX },
    CpuInstructionData { instruction: CMP, mode: AbsoluteLongX },
    // 0xe0 - 0xef
    CpuInstructionData { instruction: CPX, mode: ImmediateXFlag },
    CpuInstructionData { instruction: SBC, mode: IndexedIndirectX },
    CpuInstructionData { instruction: SEP, mode: ImmediateByte },
    CpuInstructionData { instruction: SBC, mode: StackRelative },
    CpuInstructionData { instruction: CPX, mode: Direct },
    CpuInstructionData { instruction: SBC, mode: Direct },
    CpuInstructionData { instruction: INC, mode: Direct },
    CpuInstructionData { instruction: SBC, mode: IndirectLong },
    CpuInstructionData { instruction: INX, mode: Implied },
    CpuInstructionData { instruction: SBC, mode: ImmediateMFlag },
    CpuInstructionData { instruction: NOP, mode: Implied },
    CpuInstructionData { instruction: XBA, mode: Implied },
    CpuInstructionData { instruction: CPX, mode: Absolute },
    CpuInstructionData { instruction: SBC, mode: Absolute },
    CpuInstructionData { instruction: INC, mode: Absolute },
    CpuInstructionData { instruction: SBC, mode: AbsoluteLong },
    // 0xf0 - 0xff
    CpuInstructionData { instruction: BEQ, mode: PcRelative },
    CpuInstructionData { instruction: SBC, mode: IndirectIndexedY },
    CpuInstructionData { instruction: SBC, mode: Indirect },
    CpuInstructionData { instruction: SBC, mode: StackRelativeIndirectIndexed },
    CpuInstructionData { instruction: PEA, mode: Absolute },
    CpuInstructionData { instruction: SBC, mode: DirectIndexedX },
    CpuInstructionData { instruction: INC, mode: DirectIndexedX },
    CpuInstructionData { instruction: SBC, mode: IndirectIndexedYLong },
    CpuInstructionData { instruction: SED, mode: Implied },
    CpuInstructionData { instruction: SBC, mode: AbsoluteY },
    CpuInstructionData { instruction: PLX, mode: Implied },
    CpuInstructionData { instruction: XCE, mode: Implied },
    CpuInstructionData { instruction: JSR, mode: AbsoluteIndirectIndexed },
    CpuInstructionData { instruction: SBC, mode: AbsoluteX },
    CpuInstructionData { instruction: INC, mode: AbsoluteX },
    CpuInstructionData { instruction: SBC, mode: AbsoluteLongX },
];
